services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkis-history
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PORT: ${PORT:-3000}
      DB_PATH: /app/data/data.db
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - ./data:/app/data
